services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: db01
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: django-backend
    environment:
      DATABASE_URL: postgres://admin:password123@postgres:5432/db01
    ports:
      - "8000:8000"
    # volumes:
    #   - ./backend:/app
    depends_on:
      - postgres

volumes:
  postgres_data:
